### ISSUE TITLE
Can't run content-collections in jest when using MDX

### ISSUE THREAD

**Issue by Xe** [sdorra/content-collections#329]
Hey,

I'm trying to add some tests to my generated blog pages to test for things like titles being rendered and the like. When I try to run this test:

```jsx
import "@testing-library/jest-dom";
import { render, screen } from "@testing-library/react";
import BlogPage from "@/app/blog/[...slug]/page";
import { describe, expect, test, it } from "@jest/globals";
import { allPosts } from "@/.content-collections/generated";

test.each(allPosts)("BlogPage $slug", (p) => {
  render(<BlogPage params={{ slug: p._meta.path.split("/") }} />);

  it("properly renders the title", () => {
    const heading = screen.getByRole("heading", {
      level: 1,
      name: p.title,
    });

    expect(heading)
      //@ts-ignore
      .toBeInTheDocument();
  });
});
```

I get an error about the import statement not being allowed:

```
 FAIL  __tests__/app/blog/[...slug]/page.test.jsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/cadey/Code/Techaro/www/node_modules/@content-collections/mdx/dist/react/client.js:2
    import { getMDXComponent } from "mdx-bundler/client/index.js";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      21 |   return null;
      22 | };
    > 23 |
         | ^
      24 | export default async function Page({ params }: { params: PageParams }) {
      25 |   const page = getPost(params.slug!);
      26 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (app/blog/[...slug]/page.tsx:23:16)
      at Object.<anonymous> (__tests__/app/blog/[...slug]/page.test.jsx:8:54)
  ```
  
  Is there an easy way to fix this or am I going to have to PR renaming all of the things in the MDX package to `.mjs` files?

**Comment by sdorra** [comment]
@Xe could you please test the preview package provided by #330

```bash
pnpm add https://pkg.pr.new/sdorra/content-collections/@content-collections/mdx@330
```

**Comment by Xe** [comment]
Will do!
