### ISSUE TITLE
Error: configuration file content-collections.ts is invalid

### ISSUE THREAD

**Issue by kamiljaneczek** [sdorra/content-collections#436]
I have brand new Next.js 15 application and then I followed installation steps.

Here is my content-collections.ts: 
````javascript
import { defineCollection, defineConfig } from "@content-collections/core";

const posts = defineCollection({
  name: "posts",
  directory: "posts",
  include: "**/*.md",
  schema: (z) => ({
    title: z.string(),
    summary: z.string(),
  }),
});

export default defineConfig({
  collections: [posts],
});
````
I receive following error:
````bash
X [ERROR] Unexpected end of file in JSON

    ../../tsconfig.json:1:1:
      1 │
        ╵  ^

file:///C:/Dev/webforma/node_modules/@clerc/core/dist/index.js:296
        __privateMethod(this, _handleError, handleError_fn).call(this, new Error(msg));
                                                                       ^

Error: configuration file content-collections.ts is invalid: Error: Build failed with 1 error:
../../tsconfig.json:1:1: ERROR: Unexpected end of file in JSON
    at LiteEmit.errorHandler (file:///C:/Dev/webforma/node_modules/@clerc/core/dist/index.js:296:72)
    at file:///C:/Dev/webforma/node_modules/lite-emit/dist/index.mjs:67:80
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

````
Anyone seen similar problems? I was using sometime ago with Next 14 and it was working fine at that time.

**Comment by kamiljaneczek** [comment]
I am using it inside my monorepo: turborepo

**Comment by sdorra** [comment]
@kamiljaneczek I don't think the problem lies in the content collections configuration. It seems the issue is with the `tsconfig.json`; the error suggests that the file may be empty. Can you check your `tsconfig.json` files?

**Comment by IanMitchell** [comment]
I'm seeing something similar but slightly different, also in a turborepo monorepo:

```
│ Starting content-collections content-collections.ts
│
│ > Build error occurred
│ [Error: configuration file content-collections.ts is invalid: Error: The service was stopped: write EPIPE] {
│   type: 'Compile'
│ }
```

Poking around the source to see if anything stands out
